openapi: 3.0.0
# Added by Open API https://swagger.io/tools/swaggerhub/

servers:
  - description: Iris Service
    url: http://0.0.0.0/IRIS/1.0.0
info:
  description: Iris Model Service
  version: "1.0.0"
  title: iris service api
  contact:
    email: qunfei.wu@outlook.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
- name: iris

paths:
  /predicate:
    get:
      summary: predicate one iris flower
      operationId: predicateOneIris
      description: predicate one iris flower
      tags: [iris]
      parameters:
        - in: query
          name: petal_length
          required: false
          schema:
            type: number
            format: float
        - in: query
          name: petal_width
          schema:
            type: number
            format: float
        - in: query
          name: sepal_length
          schema:
            type: number
            format: float
        - in: query
          name: sepal_width
          schema:
            type: number
            format: float
      responses:
        '200':
          description: iris specie
          content:
            text/plain:
              schema:
                type: string
                example: 'setosa'
        '400':
          description: bad input parameter
        '404':
          description: server address not exist
        '500':
          description: server error
